---
apiVersion: v1
kind: Namespace
metadata:
    name: dev

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ci-cd-dev
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ci-cd-dev
    spec:
      containers:
        - image: ahprosim/ci-cd-dev:<BUILD_TAG>
          imagePullPolicy: IfNotPresent
          name: ci-cd-dev
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 128Mi
          ports:
            - containerPort: 5000
              name: web
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 12

          env:
           - name: ENV
             value: <ENV_MODE>

---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-dev-service
  namespace: dev
  labels:
    app: ci-cd-dev
spec:
  selector:
    app: ci-cd-dev
  type: NodePort
  ports:
    - name: web
      port: 5000
      targetPort: web
      nodePort: 30002